USE vk;
ALTER TABLE messages DROP PRIMARY KEY;
ALTER TABLE messages ADD PRIMARY KEY (from_user_id, to_user_id, created_at);
DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
  id int(10) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id int(10) unsigned NOT NULL,
  body text COLLATE utf8_unicode_ci NOT NULL,
  created_at datetime DEFAULT current_timestamp()
);
DROP TABLE IF EXISTS newsline;
CREATE TABLE newsline (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  body TEXT NOT NULL,
  created_at DATETIME DEFAULT NOW()
);
DROP TABLE IF EXISTS likes;
CREATE TABLE likes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  like_type_id INT UNSIGNED NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS like_types;
CREATE TABLE like_types (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);
